version: '2'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app/static
      - /Users/Henrik/testdoc3psql/web:/usr/src/app
    command: /usr/local/bin/gunicorn -w 1 -b :8000 app:app
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"
  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
